version: "3.8"

services:
  api:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    environment:
      - SERVER_HOST=https://127.0.0.1:8000
    depends_on:
      - mongo
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/BookStore/
    # env_file:
    #   - .env    
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: ./start.sh

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

